# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_id', models.IntegerField(db_index=True)),
                ('x', models.IntegerField(db_index=True)),
                ('y', models.IntegerField(db_index=True)),
                ('z', models.IntegerField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('allegiance', models.CharField(max_length=50)),
                ('allegiance_id', models.IntegerField()),
                ('edsm_id', models.IntegerField(db_index=True)),
                ('controlling_minor_faction', models.CharField(max_length=50)),
                ('controlling_minor_faction_id', models.IntegerField()),
                ('government', models.CharField(max_length=50)),
                ('government_id', models.IntegerField()),
                ('power', models.CharField(max_length=50)),
                ('power_state', models.CharField(max_length=50)),
                ('power_state_id', models.IntegerField()),
                ('primary_economy', models.CharField(max_length=50)),
                ('primary_economy_id', models.IntegerField()),
                ('security', models.CharField(max_length=50)),
                ('security_id', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('state_id', models.IntegerField()),
                ('needs_permit', models.BooleanField(db_index=True)),
                ('population', models.IntegerField()),
            ],
        ),
    ]
