# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddb', '0002_auto_20171029_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='allegiance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='allegiance_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
