# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddb', '0004_auto_20171029_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='x',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='y',
            field=models.FloatField(db_index=True),
        ),
        migrations.AlterField(
            model_name='system',
            name='z',
            field=models.FloatField(db_index=True),
        ),
    ]
