# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eddb', '0005_auto_20171103_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(db_index=True)),
                ('distance_to_star', models.FloatField(db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('max_landing_pad_size', models.CharField(max_length=8)),
                ('allegiance', models.CharField(blank=True, max_length=50, null=True)),
                ('allegiance_id', models.IntegerField(blank=True, null=True)),
                ('controlling_minor_faction_id', models.IntegerField(blank=True, null=True)),
                ('government', models.CharField(blank=True, max_length=50, null=True)),
                ('government_id', models.IntegerField(blank=True, null=True)),
                ('has_blackmarket', models.BooleanField()),
                ('has_commodities', models.BooleanField()),
                ('has_docking', models.BooleanField()),
                ('has_market', models.BooleanField()),
                ('has_outfitting', models.BooleanField()),
                ('has_rearm', models.BooleanField()),
                ('has_refuel', models.BooleanField()),
                ('has_repair', models.BooleanField()),
                ('has_shipyard', models.BooleanField()),
                ('is_planetary', models.BooleanField()),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('power', models.CharField(blank=True, max_length=50, null=True)),
                ('power_state', models.CharField(blank=True, max_length=50, null=True)),
                ('power_state_id', models.IntegerField(blank=True, null=True)),
                ('primary_economy', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_economy_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('type_id', models.IntegerField(blank=True, null=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eddb.System')),
            ],
        ),
    ]
