# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddb', '0006_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='power',
        ),
        migrations.RemoveField(
            model_name='station',
            name='power_state',
        ),
        migrations.RemoveField(
            model_name='station',
            name='power_state_id',
        ),
        migrations.RemoveField(
            model_name='station',
            name='primary_economy',
        ),
        migrations.RemoveField(
            model_name='station',
            name='primary_economy_id',
        ),
        migrations.AlterField(
            model_name='station',
            name='distance_to_star',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
