# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-04 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eddb', '0007_auto_20171104_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='max_landing_pad_size',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
